### ISSUE TITLE
Data fetch on Frontend

### ISSUE THREAD

**Issue by Aadi-Tyagi** [sambitos23/B2B-Invoice-Management-System#1]
My backend is able to fetch the data from sql database but it is not showing up on the frontend part. Could you please help
![frontend](https://user-images.githubusercontent.com/87977583/168282166-e2326332-347a-4454-a91e-1a78725ffffc.png)
![backend (1)](https://user-images.githubusercontent.com/87977583/168282221-b001fb7e-1e2d-40be-b607-4c02b11523eb.png)

**Comment by sambitos23** [comment]
Hey @Aadi-Tyagi ,
in my frontend code where the table is present -> https://github.com/sambitos23/B2B-Invoice-Management-System/blob/master/Frontend%20-%20React%20Js/src/Components/Table.js check the line no 70

you will get the fetch link which is /view but in the screenshot, I see the JDBC URL is /Demo

Please change this  /view->/Demo,  you will see the table in the frontend

**Comment by Aadi-Tyagi** [comment]
hey @sambitos23 
I have already changed the URL to /Demo but still, nothing is showing up
![table](https://user-images.githubusercontent.com/87977583/168414896-79ca0c47-1f1b-45c5-aec4-87b27bd6d34a.png)

**Comment by sambitos23** [comment]
Can you please check the console of your browser @Aadi-Tyagi what error u have? and send me the SS

**Comment by Aadi-Tyagi** [comment]
![image](https://user-images.githubusercontent.com/87977583/168417156-ce87e752-6c30-430f-915d-4c2a07f70078.png)

**Comment by sambitos23** [comment]
yes I also think
This is the cors policy error
Have you wholly downloaded my whole project or copied a few parts?

**Comment by sambitos23** [comment]
pls check this https://github.com/sambitos23/B2B-Invoice-Management-System/blob/master/Backend%20-%20JDBC%20Servalate%20-%20Java/WebContent/WEB-INF/web.xml
and copied the whole web.xml

**Comment by sambitos23** [comment]
if it does not work connect with me in meet -> https://bit.ly/createsambit
just comment join now, I will join

**Comment by Aadi-Tyagi** [comment]
Thank you for all your help. It was the same cors policy error as u pointed out. I forgot to add it, in the web.xml file. Now everything is working as expected.

**Comment by sambitos23** [comment]
Good to know, your problem is solved. Please give the star to the project so that it will reach further.
